add status report to workflow

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -18,18 +18,28 @@ jobs:
         with:
           python-version: "3.11" # install the python version needed
 
-      - name: execute py script # run main.py
+      - name: Check, sort and consolidate data
+        id: consolidate
         working-directory: .
         run: python .github/workflows/main.py
 
-      - name: commit files
+      - name: Check script outcome
+        run: |
+          if [ ${{ steps.consolidate.outcome }} != 'success' ]; then
+            echo "Sorting and consolidation of data failed, data invalid"
+            exit 1
+          fi
+
+      - if: ${{ steps.consolidate.outcome == 'success' }}
+        name: commit files
         run: |
           git config --local user.email "action@github.com"
           git config --local user.name "GitHub Action"
           git add -A
           git diff-index --quiet HEAD || (git commit -a -m "Consolidated and formatted data" --allow-empty)
 
-      - name: push changes
+      - if: ${{ steps.consolidate.outcome == 'success' }}
+        name: push changes
         uses: ad-m/github-push-action@v0.6.0
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
